### ISSUE TITLE
编不过，求帮助

### ISSUE THREAD

**Issue by lchb369** [reactnativecomponent/react-native-chat-demo#1]
#

/Users/changbinliu/react-native-chat-demo/node_modules/react-native-netease-im/ios/RNNeteaseIm/RNNeteaseIm/PrefixHeader.pch:10:9: 'NIMSDK.h' file not found

![p](https://cloud.githubusercontent.com/assets/5262407/26812504/a273d37e-4aaa-11e7-86e5-2b50501abc59.png)

**Comment by hzlgit** [comment]
iOS 需要cocoapods安装

**Comment by lchb369** [comment]
多谢，这个问题解决了，又报了另两个错。/Users/changbinliu/react-native-chat-demo/ios/ImDemo/AppDelegate.m:12:9: 'React/RCTBundleURLProvider.h' file not found    
![1](https://cloud.githubusercontent.com/assets/5262407/26814742/6af6c216-4aba-11e7-974d-0a54ae195dad.png)

**Comment by lchb369** [comment]
还有个问题，ld: library not found for -lCocoaLumberjack
麻烦帮忙看下，或者加我下微信lchb5288
![2](https://cloud.githubusercontent.com/assets/5262407/26815767/c4e7616c-4ac0-11e7-84fb-4f62c6217d74.png)

**Comment by hzlgit** [comment]
这是因为库的路径找不到，你看一下pods文件夹里面 `CocoaLumberjack `库有没有安装成功

**Comment by lchb369** [comment]
pods文件夹里有这个目录，但好像没有编译。

**Comment by hzlgit** [comment]
你把xcode的目录截图看看

**Comment by lchb369** [comment]
好的。
![3](https://cloud.githubusercontent.com/assets/5262407/26817539/98779904-4ac9-11e7-9baa-091f6c671d5c.png)

![5](https://cloud.githubusercontent.com/assets/5262407/26817742/605d0b20-4aca-11e7-93b5-3c88af3a52ac.png)

![4](https://cloud.githubusercontent.com/assets/5262407/26817735/550ffaa2-4aca-11e7-973a-7a367898e915.png)

**Comment by hzlgit** [comment]
你要打开的不是`.xcodeproj`而是`.xcworkspace`

**Comment by lchb369** [comment]
哈，运行起来啦，好像少了张图片
![7](https://cloud.githubusercontent.com/assets/5262407/26818050/d6748364-4acb-11e7-93d1-7a8a50d2f5f9.png)

**Comment by hzlgit** [comment]
这个我修复过了，你更新一下这个文件即可

**Comment by lchb369** [comment]
嗯。运行起来了，但是登录不进去，我看云信文档，测试时可以不设置cerName   [[NIMSDK sharedSDK] registerWithAppID:@"71332a305e72c1bfff5c2a3e0ffb45fe" cerName:nil];

测试帐号:test1   密码:123abc


![9](https://cloud.githubusercontent.com/assets/5262407/26820987/611c3ace-4ad7-11e7-9ad0-a74ca01315be.png)

**Comment by hzlgit** [comment]
你把`Login.js` 里面对密码的md5加密去掉，或者在后台输入的密码进行md5加密。

**Comment by lchb369** [comment]
可以啦，多谢。

**Comment by lchb369** [comment]
老大，你是怎么开多个实例，调试的呢。

**Comment by lchb369** [comment]
我在真机上开了一个，在模拟器上开了一个，不能加好友。添加没反应。

**Comment by lchb369** [comment]
不能加好友。点击添加到通讯录 按钮没有反应，打log  这个添加好友事件没有触发。

**Comment by hzlgit** [comment]
那就是添加失败了，添加成功会有提示的。

**Comment by Sxiaobai** [comment]
![Uploading E4A21E90-8239-4D2C-AE22-7EA9E61FB834.png…]()

**Comment by Sxiaobai** [comment]
![rn](https://user-images.githubusercontent.com/14013363/26960505-7c54ceac-4d0a-11e7-954f-0fdf0e699074.png)
求支援

**Comment by hzlgit** [comment]
@Sxiaobai 你库还没安装，进入项目目录执行` npm install`

**Comment by Sxiaobai** [comment]
@hzlgit 没有执行完之后还是报这个错

**Comment by Sxiaobai** [comment]
@hzlgit 没用  执行完还是报这个错

**Comment by cielu** [comment]
@Sxiaobai  安卓用的正常啊，但是我没用ios，没证书。。。你可以先试试android

**Comment by cielu** [comment]
@hzlgit 老大，是时候组件一个交流群了啊。。。日后定有大用。。。

我们遇到的坑就找你，后来者遇到的坑，就找我们。。这样您也省事不。。


哈哈哈

**Comment by cielu** [comment]
@hzlgit @xhp @lchb369 @Sxiaobai 

创建了一个云信的 RN开发交流Q群，欢迎各位老大加入: 153174456

![image](https://user-images.githubusercontent.com/13715811/27003056-6375f6b8-4e22-11e7-9a61-48fec52a3482.png)

**Comment by hzlgit** [comment]
@Sxiaobai 这个错误是因为库找不到，你要确定你的 /node-modules 目录下面找得到相应的库

**Comment by luojf945** [comment]
@lchb369 ,我也遇到library not found for -lCocoaLumberjack问题了，请问你是怎么解决的呢？

**Comment by evanywang** [comment]
我用webstorm run的时候，遇到了下面的错误。
-------------------------------------
The following build commands failed:
	CpResource /Users/evanywang/1_workspace/1_react-native/open-source/react-native-chat-demo/node_modules/native-base/Fonts/Andale\ Mono.ttf build/Build/Products/Debug-iphonesimulator/ImDemo.app/Andale\ Mono.ttf

	CpResource /Users/evanywang/1_workspace/1_react-native/open-source/react-native-chat-demo/node_modules/native-base/Fonts/Arial.ttf build/Build/Products/Debug-iphonesimulator/ImDemo.app/Arial.ttf
	CpResource /Users/evanywang/1_workspace/1_react-native/open-source/react-native-chat-demo/node_modules/native-base/Fonts/Comic\ Sans\ MS.ttf build/Build/Products/Debug-iphonesimulator/ImDemo.app/Comic\ Sans\ MS.ttf
	CpResource /Users/evanywang/1_workspace/1_react-native/open-source/react-native-chat-demo/node_modules/native-base/Fonts/Courier\ New.ttf build/Build/Products/Debug-iphonesimulator/ImDemo.app/Courier\ New.ttf
	CpResource /Users/evanywang/1_workspace/1_react-native/open-source/react-native-chat-demo/node_modules/native-base/Fonts/Arial\ Black.ttf build/Build/Products/Debug-iphonesimulator/ImDemo.app/Arial\ Black.ttf
(5 failures)

**Comment by hzlgit** [comment]
@evanywang 删除找不到的文件就可以了
