### ISSUE TITLE
发音发送失败

### ISSUE THREAD

**Issue by eurekao** [reactnativecomponent/react-native-chat-demo#10]
第一次发送语音成功，但是聊天界面不会显示发送的语言，返回到会话页面后再次进入到聊天页面可以看到刚才发送的语言，但是此时无法再发送语言，点击“按住 说话”会提示：“请在应用的权限管理中将使用录音选项设置为允许，否则将无法使用录音功能”

**Comment by hzlgit** [comment]
@eurekao 这些问题,更新ui库以及demo的代码即可解决
