### ISSUE TITLE
按返回键隐藏ActionBar

### ISSUE THREAD

**Issue by eurekao** [reactnativecomponent/react-native-chat-demo#12]
android平台，在ActionBar显示的状态下，按返回键应该隐藏ActionBar

**Comment by hzlgit** [comment]
@eurekao 哪个ActionBar

**Comment by eurekao** [comment]
@hzlgit 点击+号以后弹出的面板，面板弹出状态下，按返回键，直接页面就退出来了(输入法面板显示的时候，能够正常关闭输入法)

**Comment by hzlgit** [comment]
@eurekao 我不太明白你想要达到的预期

**Comment by hzlgit** [comment]
我明白你的意思了，你只需要监听BackHandler事件处理即可
