### ISSUE TITLE
老大，那个r-n-gifted-chat 有问题，点开聊天列表要等半天才显示聊天记录，用户体验很不好

### ISSUE THREAD

**Issue by cielu** [reactnativecomponent/react-native-chat-demo#2]
然后的话，中间还有蛮多问题的，还有就是现在不是 react-navigation 很流行吗？为什么选了 react-native-navigate呢

顺便发个云信rn交流群：153174456

**Comment by hzlgit** [comment]
因为 react-native-navigation是原生的导航，我觉得它解决了许多js导航器无法解决的问题。至于gifted-chat让初始化的早一些就可以了。

**Comment by hzlgit** [comment]
可以尝试新的原生UI，交流群我放到了readme里面了。
