### ISSUE TITLE
建议针对ReactNative出一份文档

### ISSUE THREAD

**Issue by yubo725** [reactnativecomponent/react-native-chat-demo#7]

**Comment by hzlgit** [comment]
@yubo725 具体是指？

**Comment by 594904020** [comment]
@hzlgit    楼上具体指  建议在README.md中 说明一下 js API 的调用文档，比如react-native中如何添加好友，如果创建群聊等的文档。最后在这里感谢一下大神的付出

**Comment by haiifeng** [comment]
建议加一个rn的文档。同事开放功能，让更多的人来共同维护这个组件。

**Comment by haiifeng** [comment]
后期也可以把其他功能加进来，比如视频直播点播。或者新启一个项目也可以的。

**Comment by meiqi1992** [comment]
+1

**Comment by NikiLee2016** [comment]
+1

**Comment by gitfdy** [comment]
网易不收钱给你服务就不错了,还想要出文档.....

**Comment by haiifeng** [comment]
+1 
现在rn的文档及其难懂，需要来回查找相关文档。
涉及到原生的比如推送之类的，对于前端来说有很大难度去研究，真诚建议将这块更加详细说明下。

**Comment by lostomato** [comment]
这个demo有音视频即时通信功能吗

**Comment by DarkerMace** [comment]
点击输入崩溃

**Comment by hzlgit** [comment]
@lostomato 因为收费的原因，不太好做
音视频的可以看这个，https://github.com/syanbo/react-native-agora
