### ISSUE TITLE
第一次编译还正常，第二次就这样了Execution failed for task ':app:transformNative_libsWithStripDebugSymbolForDebug‘

### ISSUE THREAD

**Issue by hawind** [reactnativecomponent/react-native-chat-demo#8]
![image](https://user-images.githubusercontent.com/11567857/31008424-ab1f84fa-a536-11e7-9cca-f70c1a0d38f9.png)

**Comment by hawind** [comment]
而且感觉依赖了很多东西在里面，最后在说一下网易IM，有严重的坑，超过100人，消息发不出去，但是后台并没有限制100人，这个demo里，包含了极光的开源库，网易的，还有其他的一些东西，编译的时候巨慢

**Comment by hzlgit** [comment]
聊天的ui库为了更多的定制当然需要跟多的依赖，提供了更多的选择。100人是因为免费的限制就是100用户数，官方有写。至于编译的错误，不存在第一次和第二次的问题，肯定是有地方处理不当，上图提供的信息看不出来错误再哪里。编译慢是因为multiDex。

**Comment by hzlgit** [comment]
@hawind 建议使用AS，这样能帮助你更容易找到原因所在。

**Comment by hawind** [comment]
@hzlgit 好的，主要是觉得AS很卡，好像是因为ndk版本太低了，之前编译没有这个错误提示，设置了NDK才提示的，新手入坑RN
